a = int(input("Enter First Number:"))
b = int(input("Enter Second NUmber:"))

add =(a + b)
print("Addition:", add)
sub=(a - b)
print("Subtraction:", sub)
mul=(a * b)
print("Multiplication:", mul)
div=(a / b)
print("Division:",round(div))
